let a = 5;
let b = "CodeWithFalcon";
let c = Boolean(true);
let d = BigInt("200")+("100");
let e = Symbol("CodeWithFalcon");
let f = null;
let g = undefined;
// console.log(a);
// console.log(b);
// console.log(c);
// console.log(d);
// console.log(e); 
// console.log(f); 
// console.log(g); 
console.log(typeof(a));
console.log(typeof(b));
console.log(typeof(c));
console.log(typeof(d));
console.log(typeof(e));
console.log(typeof(f));
console.log(typeof(g));